// <auto-generated />
namespace OfflineMessagesApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class readAndReceivedColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(readAndReceivedColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201707201633374_readAndReceivedColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
