// <auto-generated />
namespace OfflineMessagesApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class upddateUserBlockTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upddateUserBlockTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201707200514021_upddateUserBlockTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
